create table tb_telefones(
id BIGINT generated by default as identity,
numero VARCHAR(20) NOT NULL,
primary key(id)
);

create table tb_enderecos(
id BIGINT generated by default as identity,
endereco VARCHAR(100) NOT NULL,
primary key(id)
);

create table tb_horarios(
id BIGINT generated by default as identity,
horario VARCHAR(50) NOT NULL,
primary key(id)
);

insert into TB_TELEFONES(numero) values
('51 98299-9984'),
('51 34582795'),
('55 98733-2525'),
('51 98114-9691');

insert into TB_ENDERECOS(endereco) values
('Rua travessa mem de sa 91'),
('Avenida presidente vargas 1999'),
('Rua da figueira 231'),
('Rodovia BR 116 KM 20 SAO LEOPOLDO 1223');

insert into TB_HORARIOS(horario) values
('SEG A SAB 08h as 22h'),
('DOMINGO 14h as 20h'),
('FERIADOS 14h as 20h');