create table tb_telefones(
id BIGINT generated by default as identity,
numero VARCHAR(20) NOT NULL,
primary key(id)
);

insert into TB_TELEFONES(numero) values
('51 98299-9984'),
('51 34582795'),
('55 98733-2525'),
('51 98114-9691');